-- ==============================================
-- 若依系统初始化SQL（DB2 11.5+版本）
-- 执行前请确保已切换到RY模式：SET SCHEMA RY;
-- ==============================================

-- ----------------------------
-- 1、部门表
-- ----------------------------
DROP TABLE IF EXISTS SYS_DEPT;
CREATE TABLE SYS_DEPT (
                          DEPT_ID           BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                          PARENT_ID         BIGINT          NOT NULL DEFAULT 0,
                          ANCESTORS         VARCHAR(50)     NOT NULL DEFAULT '',
                          DEPT_NAME         VARCHAR(30)     NOT NULL DEFAULT '',
                          ORDER_NUM         INTEGER         NOT NULL DEFAULT 0,
                          LEADER            VARCHAR(20)     DEFAULT NULL,
                          PHONE             VARCHAR(11)     DEFAULT NULL,
                          EMAIL             VARCHAR(50)     DEFAULT NULL,
                          STATUS            CHAR(1)         NOT NULL DEFAULT '0',
                          DEL_FLAG          CHAR(1)         NOT NULL DEFAULT '0',
                          CREATE_BY         VARCHAR(64)     NOT NULL DEFAULT '',
                          CREATE_TIME       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          UPDATE_BY         VARCHAR(64)     NOT NULL DEFAULT '',
                          UPDATE_TIME       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          PRIMARY KEY (DEPT_ID)
);
-- 单独添加列注释
COMMENT ON COLUMN SYS_DEPT.DEPT_ID IS '部门id';
COMMENT ON COLUMN SYS_DEPT.PARENT_ID IS '父部门id';
COMMENT ON COLUMN SYS_DEPT.ANCESTORS IS '祖级列表';
COMMENT ON COLUMN SYS_DEPT.DEPT_NAME IS '部门名称';
COMMENT ON COLUMN SYS_DEPT.ORDER_NUM IS '显示顺序';
COMMENT ON COLUMN SYS_DEPT.LEADER IS '负责人';
COMMENT ON COLUMN SYS_DEPT.PHONE IS '联系电话';
COMMENT ON COLUMN SYS_DEPT.EMAIL IS '邮箱';
COMMENT ON COLUMN SYS_DEPT.STATUS IS '部门状态（0正常 1停用）';
COMMENT ON COLUMN SYS_DEPT.DEL_FLAG IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN SYS_DEPT.CREATE_BY IS '创建者';
COMMENT ON COLUMN SYS_DEPT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_DEPT.UPDATE_BY IS '更新者';
COMMENT ON COLUMN SYS_DEPT.UPDATE_TIME IS '更新时间';
COMMENT ON TABLE SYS_DEPT IS '部门表';

-- 初始化-部门表数据（移除自增ID手动赋值）
INSERT INTO SYS_DEPT (PARENT_ID, ANCESTORS, DEPT_NAME, ORDER_NUM, LEADER, PHONE, EMAIL, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES(0,   '0',          '若依科技',   0, '若依', '15888888888', 'ry@qq.com', '0', '0', 'admin', CURRENT_TIMESTAMP);
INSERT INTO SYS_DEPT (PARENT_ID, ANCESTORS, DEPT_NAME, ORDER_NUM, LEADER, PHONE, EMAIL, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES(100, '0,100',      '深圳总公司', 1, '若依', '15888888888', 'ry@qq.com', '0', '0', 'admin', CURRENT_TIMESTAMP);
INSERT INTO SYS_DEPT (PARENT_ID, ANCESTORS, DEPT_NAME, ORDER_NUM, LEADER, PHONE, EMAIL, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES(100, '0,100',      '长沙分公司', 2, '若依', '15888888888', 'ry@qq.com', '0', '0', 'admin', CURRENT_TIMESTAMP);
INSERT INTO SYS_DEPT (PARENT_ID, ANCESTORS, DEPT_NAME, ORDER_NUM, LEADER, PHONE, EMAIL, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES(101, '0,100,101',  '研发部门',   1, '若依', '15888888888', 'ry@qq.com', '0', '0', 'admin', CURRENT_TIMESTAMP);
INSERT INTO SYS_DEPT (PARENT_ID, ANCESTORS, DEPT_NAME, ORDER_NUM, LEADER, PHONE, EMAIL, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES(101, '0,100,101',  '市场部门',   2, '若依', '15888888888', 'ry@qq.com', '0', '0', 'admin', CURRENT_TIMESTAMP);
INSERT INTO SYS_DEPT (PARENT_ID, ANCESTORS, DEPT_NAME, ORDER_NUM, LEADER, PHONE, EMAIL, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES(101, '0,100,101',  '测试部门',   3, '若依', '15888888888', 'ry@qq.com', '0', '0', 'admin', CURRENT_TIMESTAMP);
INSERT INTO SYS_DEPT (PARENT_ID, ANCESTORS, DEPT_NAME, ORDER_NUM, LEADER, PHONE, EMAIL, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES(101, '0,100,101',  '财务部门',   4, '若依', '15888888888', 'ry@qq.com', '0', '0', 'admin', CURRENT_TIMESTAMP);
INSERT INTO SYS_DEPT (PARENT_ID, ANCESTORS, DEPT_NAME, ORDER_NUM, LEADER, PHONE, EMAIL, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES(101, '0,100,101',  '运维部门',   5, '若依', '15888888888', 'ry@qq.com', '0', '0', 'admin', CURRENT_TIMESTAMP);
INSERT INTO SYS_DEPT (PARENT_ID, ANCESTORS, DEPT_NAME, ORDER_NUM, LEADER, PHONE, EMAIL, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES(102, '0,100,102',  '市场部门',   1, '若依', '15888888888', 'ry@qq.com', '0', '0', 'admin', CURRENT_TIMESTAMP);
INSERT INTO SYS_DEPT (PARENT_ID, ANCESTORS, DEPT_NAME, ORDER_NUM, LEADER, PHONE, EMAIL, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES(102, '0,100,102',  '财务部门',   2, '若依', '15888888888', 'ry@qq.com', '0', '0', 'admin', CURRENT_TIMESTAMP);

-- ----------------------------
-- 2、用户信息表
-- ----------------------------
DROP TABLE IF EXISTS SYS_USER;
CREATE TABLE SYS_USER (
                          USER_ID           BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                          DEPT_ID           BIGINT          DEFAULT NULL,
                          USER_NAME         VARCHAR(30)     NOT NULL,
                          NICK_NAME         VARCHAR(30)     NOT NULL,
                          USER_TYPE         VARCHAR(2)      NOT NULL DEFAULT '00',
                          EMAIL             VARCHAR(50)     NOT NULL DEFAULT '',
                          PHONENUMBER       VARCHAR(11)     NOT NULL DEFAULT '',
                          SEX               CHAR(1)         NOT NULL DEFAULT '0',
                          AVATAR            VARCHAR(100)    NOT NULL DEFAULT '',
                          PASSWORD          VARCHAR(100)    NOT NULL DEFAULT '',
                          STATUS            CHAR(1)         NOT NULL DEFAULT '0',
                          DEL_FLAG          CHAR(1)         NOT NULL DEFAULT '0',
                          LOGIN_IP          VARCHAR(128)    NOT NULL DEFAULT '',
                          LOGIN_DATE        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          PWD_UPDATE_DATE   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          id_token          VARCHAR(2000)   DEFAULT NULL,
                          keycloak_id       VARCHAR(200)    DEFAULT NULL,
                          access_token      VARCHAR(2000)   DEFAULT NULL,
                          CREATE_BY         VARCHAR(64)     NOT NULL DEFAULT '',
                          CREATE_TIME       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          UPDATE_BY         VARCHAR(64)     NOT NULL DEFAULT '',
                          UPDATE_TIME       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          REMARK            VARCHAR(500)    DEFAULT NULL,
                          PRIMARY KEY (USER_ID)
);
-- 单独添加列注释
COMMENT ON COLUMN SYS_USER.USER_ID IS '用户ID';
COMMENT ON COLUMN SYS_USER.DEPT_ID IS '部门ID';
COMMENT ON COLUMN SYS_USER.USER_NAME IS '用户账号';
COMMENT ON COLUMN SYS_USER.NICK_NAME IS '用户昵称';
COMMENT ON COLUMN SYS_USER.USER_TYPE IS '用户类型（00系统用户）';
COMMENT ON COLUMN SYS_USER.EMAIL IS '用户邮箱';
COMMENT ON COLUMN SYS_USER.PHONENUMBER IS '手机号码';
COMMENT ON COLUMN SYS_USER.SEX IS '用户性别（0男 1女 2未知）';
COMMENT ON COLUMN SYS_USER.AVATAR IS '头像地址';
COMMENT ON COLUMN SYS_USER.PASSWORD IS '密码';
COMMENT ON COLUMN SYS_USER.STATUS IS '账号状态（0正常 1停用）';
COMMENT ON COLUMN SYS_USER.DEL_FLAG IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN SYS_USER.LOGIN_IP IS '最后登录IP';
COMMENT ON COLUMN SYS_USER.LOGIN_DATE IS '最后登录时间';
COMMENT ON COLUMN SYS_USER.PWD_UPDATE_DATE IS '密码最后更新时间';
COMMENT ON COLUMN SYS_USER.CREATE_BY IS '创建者';
COMMENT ON COLUMN SYS_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_USER.UPDATE_BY IS '更新者';
COMMENT ON COLUMN SYS_USER.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYS_USER.REMARK IS '备注';
COMMENT ON TABLE SYS_USER IS '用户信息表';

-- 初始化-用户信息表数据（移除自增ID手动赋值）
INSERT INTO SYS_USER (USER_ID, DEPT_ID, USER_NAME, NICK_NAME, USER_TYPE, EMAIL, PHONENUMBER, SEX, AVATAR, PASSWORD, STATUS, DEL_FLAG, LOGIN_IP, LOGIN_DATE, PWD_UPDATE_DATE, CREATE_BY, CREATE_TIME, REMARK)
VALUES(1, 103, 'admin', '若依', '00', 'ry@163.com', '15888888888', '1', '', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', '127.0.0.1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, '管理员');
INSERT INTO SYS_USER (USER_ID, DEPT_ID, USER_NAME, NICK_NAME, USER_TYPE, EMAIL, PHONENUMBER, SEX, AVATAR, PASSWORD, STATUS, DEL_FLAG, LOGIN_IP, LOGIN_DATE, PWD_UPDATE_DATE, CREATE_BY, CREATE_TIME, REMARK)
VALUES(2, 105, 'ry',    '若依', '00', 'ry@qq.com',  '15666666666', '1', '', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', '127.0.0.1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, '测试员');

-- ----------------------------
-- 3、岗位信息表
-- ----------------------------
DROP TABLE IF EXISTS SYS_POST;
CREATE TABLE SYS_POST (
                          POST_ID       BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                          POST_CODE     VARCHAR(64)     NOT NULL,
                          POST_NAME     VARCHAR(50)     NOT NULL,
                          POST_SORT     INTEGER         NOT NULL,
                          STATUS        CHAR(1)         NOT NULL,
                          CREATE_BY     VARCHAR(64)     NOT NULL DEFAULT '',
                          CREATE_TIME   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          UPDATE_BY     VARCHAR(64)     NOT NULL DEFAULT '',
                          UPDATE_TIME   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          REMARK        VARCHAR(500)    DEFAULT NULL,
                          PRIMARY KEY (POST_ID)
);
-- 单独添加列注释
COMMENT ON COLUMN SYS_POST.POST_ID IS '岗位ID';
COMMENT ON COLUMN SYS_POST.POST_CODE IS '岗位编码';
COMMENT ON COLUMN SYS_POST.POST_NAME IS '岗位名称';
COMMENT ON COLUMN SYS_POST.POST_SORT IS '显示顺序';
COMMENT ON COLUMN SYS_POST.STATUS IS '状态（0正常 1停用）';
COMMENT ON COLUMN SYS_POST.CREATE_BY IS '创建者';
COMMENT ON COLUMN SYS_POST.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_POST.UPDATE_BY IS '更新者';
COMMENT ON COLUMN SYS_POST.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYS_POST.REMARK IS '备注';
COMMENT ON TABLE SYS_POST IS '岗位信息表';

-- 初始化-岗位信息表数据（移除自增ID手动赋值）
INSERT INTO SYS_POST (POST_CODE, POST_NAME, POST_SORT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('ceo',  '董事长',    1, '0', 'admin', CURRENT_TIMESTAMP, '');
INSERT INTO SYS_POST (POST_CODE, POST_NAME, POST_SORT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('se',   '项目经理',  2, '0', 'admin', CURRENT_TIMESTAMP, '');
INSERT INTO SYS_POST (POST_CODE, POST_NAME, POST_SORT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('hr',   '人力资源',  3, '0', 'admin', CURRENT_TIMESTAMP, '');
INSERT INTO SYS_POST (POST_CODE, POST_NAME, POST_SORT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('user', '普通员工',  4, '0', 'admin', CURRENT_TIMESTAMP, '');

-- ----------------------------
-- 4、角色信息表
-- ----------------------------
DROP TABLE IF EXISTS SYS_ROLE;
CREATE TABLE SYS_ROLE (
                          ROLE_ID              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                          ROLE_NAME            VARCHAR(30)     NOT NULL,
                          ROLE_KEY             VARCHAR(100)    NOT NULL,
                          ROLE_SORT            INTEGER         NOT NULL,
                          DATA_SCOPE           CHAR(1)         NOT NULL DEFAULT '1',
                          MENU_CHECK_STRICTLY  SMALLINT        NOT NULL DEFAULT 1,
                          DEPT_CHECK_STRICTLY  SMALLINT        NOT NULL DEFAULT 1,
                          STATUS               CHAR(1)         NOT NULL,
                          DEL_FLAG             CHAR(1)         NOT NULL DEFAULT '0',
                          CREATE_BY            VARCHAR(64)     NOT NULL DEFAULT '',
                          CREATE_TIME          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          UPDATE_BY            VARCHAR(64)     NOT NULL DEFAULT '',
                          UPDATE_TIME          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          REMARK               VARCHAR(500)    DEFAULT NULL,
                          PRIMARY KEY (ROLE_ID)
);
-- 单独添加列注释
COMMENT ON COLUMN SYS_ROLE.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYS_ROLE.ROLE_NAME IS '角色名称';
COMMENT ON COLUMN SYS_ROLE.ROLE_KEY IS '角色权限字符串';
COMMENT ON COLUMN SYS_ROLE.ROLE_SORT IS '显示顺序';
COMMENT ON COLUMN SYS_ROLE.DATA_SCOPE IS '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）';
COMMENT ON COLUMN SYS_ROLE.MENU_CHECK_STRICTLY IS '菜单树选择项是否关联显示';
COMMENT ON COLUMN SYS_ROLE.DEPT_CHECK_STRICTLY IS '部门树选择项是否关联显示';
COMMENT ON COLUMN SYS_ROLE.STATUS IS '角色状态（0正常 1停用）';
COMMENT ON COLUMN SYS_ROLE.DEL_FLAG IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN SYS_ROLE.CREATE_BY IS '创建者';
COMMENT ON COLUMN SYS_ROLE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_ROLE.UPDATE_BY IS '更新者';
COMMENT ON COLUMN SYS_ROLE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYS_ROLE.REMARK IS '备注';
COMMENT ON TABLE SYS_ROLE IS '角色信息表';

-- 初始化-角色信息表数据（移除自增ID手动赋值）
INSERT INTO SYS_ROLE (ROLE_NAME, ROLE_KEY, ROLE_SORT, DATA_SCOPE, MENU_CHECK_STRICTLY, DEPT_CHECK_STRICTLY, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME, REMARK)
VALUES('超级管理员',  'admin',  1, 1, 1, 1, '0', '0', 'admin', CURRENT_TIMESTAMP, '超级管理员');
INSERT INTO SYS_ROLE (ROLE_NAME, ROLE_KEY, ROLE_SORT, DATA_SCOPE, MENU_CHECK_STRICTLY, DEPT_CHECK_STRICTLY, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME, REMARK)
VALUES('普通角色',    'common', 2, 2, 1, 1, '0', '0', 'admin', CURRENT_TIMESTAMP, '普通角色');

-- ----------------------------
-- 5、菜单权限表
-- ----------------------------
DROP TABLE IF EXISTS SYS_MENU;
CREATE TABLE SYS_MENU (
                          MENU_ID           BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 2000 INCREMENT BY 1),
                          MENU_NAME         VARCHAR(50)     NOT NULL,
                          PARENT_ID         BIGINT          NOT NULL DEFAULT 0,
                          ORDER_NUM         INTEGER         NOT NULL DEFAULT 0,
                          PATH              VARCHAR(200)    NOT NULL DEFAULT '',
                          COMPONENT         VARCHAR(255)    DEFAULT NULL,
                          QUERY             VARCHAR(255)    DEFAULT NULL,
                          ROUTE_NAME        VARCHAR(50)     NOT NULL DEFAULT '',
                          IS_FRAME          SMALLINT        NOT NULL DEFAULT 1,
                          IS_CACHE          SMALLINT        NOT NULL DEFAULT 0,
                          MENU_TYPE         CHAR(1)         NOT NULL DEFAULT '',
                          VISIBLE           CHAR(1)         NOT NULL DEFAULT '0',
                          STATUS            CHAR(1)         NOT NULL DEFAULT '0',
                          PERMS             VARCHAR(100)    DEFAULT NULL,
                          ICON              VARCHAR(100)    NOT NULL DEFAULT '#',
                          CREATE_BY         VARCHAR(64)     NOT NULL DEFAULT '',
                          CREATE_TIME       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          UPDATE_BY         VARCHAR(64)     NOT NULL DEFAULT '',
                          UPDATE_TIME       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
                          REMARK            VARCHAR(500)    NOT NULL DEFAULT '',
                          PRIMARY KEY (MENU_ID)
);
-- 单独添加列注释
COMMENT ON COLUMN SYS_MENU.MENU_ID IS '菜单ID';
COMMENT ON COLUMN SYS_MENU.MENU_NAME IS '菜单名称';
COMMENT ON COLUMN SYS_MENU.PARENT_ID IS '父菜单ID';
COMMENT ON COLUMN SYS_MENU.ORDER_NUM IS '显示顺序';
COMMENT ON COLUMN SYS_MENU.PATH IS '路由地址';
COMMENT ON COLUMN SYS_MENU.COMPONENT IS '组件路径';
COMMENT ON COLUMN SYS_MENU.QUERY IS '路由参数';
COMMENT ON COLUMN SYS_MENU.ROUTE_NAME IS '路由名称';
COMMENT ON COLUMN SYS_MENU.IS_FRAME IS '是否为外链（0是 1否）';
COMMENT ON COLUMN SYS_MENU.IS_CACHE IS '是否缓存（0缓存 1不缓存）';
COMMENT ON COLUMN SYS_MENU.MENU_TYPE IS '菜单类型（M目录 C菜单 F按钮）';
COMMENT ON COLUMN SYS_MENU.VISIBLE IS '菜单状态（0显示 1隐藏）';
COMMENT ON COLUMN SYS_MENU.STATUS IS '菜单状态（0正常 1停用）';
COMMENT ON COLUMN SYS_MENU.PERMS IS '权限标识';
COMMENT ON COLUMN SYS_MENU.ICON IS '菜单图标';
COMMENT ON COLUMN SYS_MENU.CREATE_BY IS '创建者';
COMMENT ON COLUMN SYS_MENU.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_MENU.UPDATE_BY IS '更新者';
COMMENT ON COLUMN SYS_MENU.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYS_MENU.REMARK IS '备注';
COMMENT ON TABLE SYS_MENU IS '菜单权限表';

-- 初始化-菜单信息表数据（移除自增ID手动赋值）
-- 一级菜单
INSERT INTO SYS_MENU VALUES(1, '系统管理', 0, '1', 'system',           null, '', '', 1, 0, 'M', '0', '0', '', 'system',   'admin', CURRENT_TIMESTAMP, '', null, '系统管理目录');
INSERT INTO SYS_MENU VALUES(2, '系统监控', 0, '2', 'monitor',          null, '', '', 1, 0, 'M', '0', '0', '', 'monitor',  'admin', CURRENT_TIMESTAMP, '', null, '系统监控目录');
INSERT INTO SYS_MENU VALUES(3, '系统工具', 0, '3', 'tool',             null, '', '', 1, 0, 'M', '0', '0', '', 'tool',     'admin', CURRENT_TIMESTAMP, '', null, '系统工具目录');
-- INSERT INTO SYS_MENU VALUES(4, '若依官网', 0, '4', 'http://ruoyi.vip', null, '', '', 0, 0, 'M', '0', '0', '', 'guide',    'admin', CURRENT_TIMESTAMP, '', null, '若依官网地址');
-- 二级菜单
INSERT INTO SYS_MENU VALUES(100,  '用户管理', 1,   '1', 'user',       'system/user/index',        '', '', 1, 0, 'C', '0', '0', 'system:user:list',        'user',          'admin', CURRENT_TIMESTAMP, '', null, '用户管理菜单');
INSERT INTO SYS_MENU VALUES(101,  '角色管理', 1,   '2', 'role',       'system/role/index',        '', '', 1, 0, 'C', '0', '0', 'system:role:list',        'peoples',       'admin', CURRENT_TIMESTAMP, '', null, '角色管理菜单');
INSERT INTO SYS_MENU VALUES(102,  '菜单管理', 1,   '3', 'menu',       'system/menu/index',        '', '', 1, 0, 'C', '0', '0', 'system:menu:list',        'tree-table',    'admin', CURRENT_TIMESTAMP, '', null, '菜单管理菜单');
INSERT INTO SYS_MENU VALUES(103,  '部门管理', 1,   '4', 'dept',       'system/dept/index',        '', '', 1, 0, 'C', '0', '0', 'system:dept:list',        'tree',          'admin', CURRENT_TIMESTAMP, '', null, '部门管理菜单');
INSERT INTO SYS_MENU VALUES(104,  '岗位管理', 1,   '5', 'post',       'system/post/index',        '', '', 1, 0, 'C', '0', '0', 'system:post:list',        'post',          'admin', CURRENT_TIMESTAMP, '', null, '岗位管理菜单');
INSERT INTO SYS_MENU VALUES(105,  '字典管理', 1,   '6', 'dict',       'system/dict/index',        '', '', 1, 0, 'C', '0', '0', 'system:dict:list',        'dict',          'admin', CURRENT_TIMESTAMP, '', null, '字典管理菜单');
INSERT INTO SYS_MENU VALUES(106,  '参数设置', 1,   '7', 'config',     'system/config/index',      '', '', 1, 0, 'C', '0', '0', 'system:config:list',      'edit',          'admin', CURRENT_TIMESTAMP, '', null, '参数设置菜单');
INSERT INTO SYS_MENU VALUES(107,  '通知公告', 1,   '8', 'notice',     'system/notice/index',      '', '', 1, 0, 'C', '0', '0', 'system:notice:list',      'message',       'admin', CURRENT_TIMESTAMP, '', null, '通知公告菜单');
INSERT INTO SYS_MENU VALUES(108,  '日志管理', 1,   '9', 'log',        '',                         '', '', 1, 0, 'M', '0', '0', '',                        'log',           'admin', CURRENT_TIMESTAMP, '', null, '日志管理菜单');
INSERT INTO SYS_MENU VALUES(109,  '在线用户', 2,   '1', 'online',     'monitor/online/index',     '', '', 1, 0, 'C', '0', '0', 'monitor:online:list',     'online',        'admin', CURRENT_TIMESTAMP, '', null, '在线用户菜单');
INSERT INTO SYS_MENU VALUES(110,  '定时任务', 2,   '2', 'job',        'monitor/job/index',        '', '', 1, 0, 'C', '0', '0', 'monitor:job:list',        'job',           'admin', CURRENT_TIMESTAMP, '', null, '定时任务菜单');
INSERT INTO SYS_MENU VALUES(111,  '数据监控', 2,   '3', 'druid',      'monitor/druid/index',      '', '', 1, 0, 'C', '0', '0', 'monitor:druid:list',      'druid',         'admin', CURRENT_TIMESTAMP, '', null, '数据监控菜单');
INSERT INTO SYS_MENU VALUES(112,  '服务监控', 2,   '4', 'server',     'monitor/server/index',     '', '', 1, 0, 'C', '0', '0', 'monitor:server:list',     'server',        'admin', CURRENT_TIMESTAMP, '', null, '服务监控菜单');
INSERT INTO SYS_MENU VALUES(113,  '缓存监控', 2,   '5', 'cache',      'monitor/cache/index',      '', '', 1, 0, 'C', '0', '0', 'monitor:cache:list',      'redis',         'admin', CURRENT_TIMESTAMP, '', null, '缓存监控菜单');
INSERT INTO SYS_MENU VALUES(114,  '缓存列表', 2,   '6', 'cacheList',  'monitor/cache/list',       '', '', 1, 0, 'C', '0', '0', 'monitor:cache:list',      'redis-list',    'admin', CURRENT_TIMESTAMP, '', null, '缓存列表菜单');
INSERT INTO SYS_MENU VALUES(115,  '表单构建', 3,   '1', 'build',      'tool/build/index',         '', '', 1, 0, 'C', '0', '0', 'tool:build:list',         'build',         'admin', CURRENT_TIMESTAMP, '', null, '表单构建菜单');
INSERT INTO SYS_MENU VALUES(116,  '代码生成', 3,   '2', 'gen',        'tool/gen/index',           '', '', 1, 0, 'C', '0', '0', 'tool:gen:list',           'code',          'admin', CURRENT_TIMESTAMP, '', null, '代码生成菜单');
INSERT INTO SYS_MENU VALUES(117,  '系统接口', 3,   '3', 'swagger',    'tool/swagger/index',       '', '', 1, 0, 'C', '0', '0', 'tool:swagger:list',       'swagger',       'admin', CURRENT_TIMESTAMP, '', null, '系统接口菜单');
-- 三级菜单
INSERT INTO SYS_MENU VALUES(500,  '操作日志', 108, '1', 'operlog',    'monitor/operlog/index',    '', '', 1, 0, 'C', '0', '0', 'monitor:operlog:list',    'form',          'admin', CURRENT_TIMESTAMP, '', null, '操作日志菜单');
INSERT INTO SYS_MENU VALUES(501,  '登录日志', 108, '2', 'logininfor', 'monitor/logininfor/index', '', '', 1, 0, 'C', '0', '0', 'monitor:logininfor:list', 'logininfor',    'admin', CURRENT_TIMESTAMP, '', null, '登录日志菜单');
-- 用户管理按钮
INSERT INTO SYS_MENU VALUES(1000, '用户查询', 100, '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:query',          '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1001, '用户新增', 100, '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:add',            '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1002, '用户修改', 100, '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1003, '用户删除', 100, '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1004, '用户导出', 100, '5',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:export',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1005, '用户导入', 100, '6',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:import',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1006, '重置密码', 100, '7',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:resetPwd',       '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
-- 角色管理按钮
INSERT INTO SYS_MENU VALUES(1007, '角色查询', 101, '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:query',          '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1008, '角色新增', 101, '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:add',            '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1009, '角色修改', 101, '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1010, '角色删除', 101, '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1011, '角色导出', 101, '5',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:export',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
-- 菜单管理按钮
INSERT INTO SYS_MENU VALUES(1012, '菜单查询', 102, '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:query',          '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1013, '菜单新增', 102, '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:add',            '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1014, '菜单修改', 102, '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1015, '菜单删除', 102, '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
-- 部门管理按钮
INSERT INTO SYS_MENU VALUES(1016, '部门查询', 103, '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:query',          '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1017, '部门新增', 103, '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:add',            '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1018, '部门修改', 103, '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1019, '部门删除', 103, '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
-- 岗位管理按钮
INSERT INTO SYS_MENU VALUES(1020, '岗位查询', 104, '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:query',          '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1021, '岗位新增', 104, '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:add',            '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1022, '岗位修改', 104, '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1023, '岗位删除', 104, '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1024, '岗位导出', 104, '5',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:export',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
-- 字典管理按钮
INSERT INTO SYS_MENU VALUES(1025, '字典查询', 105, '1', '', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:query',          '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1026, '字典新增', 105, '2', '', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:add',            '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1027, '字典修改', 105, '3', '', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1028, '字典删除', 105, '4', '', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1029, '字典导出', 105, '5', '', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:export',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
-- 参数设置按钮
INSERT INTO SYS_MENU VALUES(1030, '参数查询', 106, '1', '', '', '', '', 1, 0, 'F', '0', '0', 'system:config:query',        '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1031, '参数新增', 106, '2', '', '', '', '', 1, 0, 'F', '0', '0', 'system:config:add',          '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1032, '参数修改', 106, '3', '', '', '', '', 1, 0, 'F', '0', '0', 'system:config:edit',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1033, '参数删除', 106, '4', '', '', '', '', 1, 0, 'F', '0', '0', 'system:config:remove',       '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1034, '参数导出', 106, '5', '', '', '', '', 1, 0, 'F', '0', '0', 'system:config:export',       '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
-- 通知公告按钮
INSERT INTO SYS_MENU VALUES(1035, '公告查询', 107, '1', '', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:query',        '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1036, '公告新增', 107, '2', '', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:add',          '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1037, '公告修改', 107, '3', '', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:edit',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1038, '公告删除', 107, '4', '', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:remove',       '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
-- 操作日志按钮
INSERT INTO SYS_MENU VALUES(1039, '操作查询', 500, '1', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:query',      '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1040, '操作删除', 500, '2', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:remove',     '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1041, '日志导出', 500, '3', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:export',     '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
-- 登录日志按钮
INSERT INTO SYS_MENU VALUES(1042, '登录查询', 501, '1', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:query',   '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1043, '登录删除', 501, '2', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:remove',  '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1044, '日志导出', 501, '3', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:export',  '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1045, '账户解锁', 501, '4', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:unlock',  '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
-- 在线用户按钮
INSERT INTO SYS_MENU VALUES(1046, '在线查询', 109, '1', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:query',       '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1047, '批量强退', 109, '2', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:batchLogout', '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1048, '单条强退', 109, '3', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:forceLogout', '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
-- 定时任务按钮
INSERT INTO SYS_MENU VALUES(1049, '任务查询', 110, '1', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:query',          '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1050, '任务新增', 110, '2', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:add',            '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1051, '任务修改', 110, '3', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1052, '任务删除', 110, '4', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1053, '状态修改', 110, '5', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:changeStatus',   '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1054, '任务导出', 110, '6', '', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:export',         '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
-- 代码生成按钮
INSERT INTO SYS_MENU VALUES(1055, '生成查询', 116, '1', '', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:query',             '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1056, '生成修改', 116, '2', '', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:edit',              '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1057, '生成删除', 116, '3', '', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:remove',            '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1058, '导入代码', 116, '4', '', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:import',            '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1059, '预览代码', 116, '5', '', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:preview',           '#', 'admin', CURRENT_TIMESTAMP, '', null, '');
INSERT INTO SYS_MENU VALUES(1060, '生成代码', 116, '6', '', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:code',              '#', 'admin', CURRENT_TIMESTAMP, '', null, '');

-- ----------------------------
-- 6、用户和角色关联表  用户N-1角色
-- ----------------------------
DROP TABLE IF EXISTS SYS_USER_ROLE;
CREATE TABLE SYS_USER_ROLE (
                               USER_ID   BIGINT NOT NULL,
                               ROLE_ID   BIGINT NOT NULL,
                               PRIMARY KEY(USER_ID, ROLE_ID)
);
-- 单独添加列注释
COMMENT ON COLUMN SYS_USER_ROLE.USER_ID IS '用户ID';
COMMENT ON COLUMN SYS_USER_ROLE.ROLE_ID IS '角色ID';
COMMENT ON TABLE SYS_USER_ROLE IS '用户和角色关联表';

-- 初始化-用户和角色关联表数据
INSERT INTO SYS_USER_ROLE VALUES (1, 1);
INSERT INTO SYS_USER_ROLE VALUES (2, 2);


-- ----------------------------
-- 7、角色和菜单关联表  角色1-N菜单
-- ----------------------------
DROP TABLE IF EXISTS SYS_ROLE_MENU;
CREATE TABLE SYS_ROLE_MENU (
                               ROLE_ID   BIGINT NOT NULL,
                               MENU_ID   BIGINT NOT NULL,
                               PRIMARY KEY(ROLE_ID, MENU_ID)
);
-- 单独添加列注释（DB2 不支持字段后直接加 COMMENT）
COMMENT ON COLUMN SYS_ROLE_MENU.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYS_ROLE_MENU.MENU_ID IS '菜单ID';
COMMENT ON TABLE SYS_ROLE_MENU IS '角色和菜单关联表';

-- 初始化-角色和菜单关联表数据
INSERT INTO SYS_ROLE_MENU VALUES (2, 1);
INSERT INTO SYS_ROLE_MENU VALUES (2, 2);
INSERT INTO SYS_ROLE_MENU VALUES (2, 3);
-- INSERT INTO SYS_ROLE_MENU VALUES (2, 4);
INSERT INTO SYS_ROLE_MENU VALUES (2, 100);
INSERT INTO SYS_ROLE_MENU VALUES (2, 101);
INSERT INTO SYS_ROLE_MENU VALUES (2, 102);
INSERT INTO SYS_ROLE_MENU VALUES (2, 103);
INSERT INTO SYS_ROLE_MENU VALUES (2, 104);
INSERT INTO SYS_ROLE_MENU VALUES (2, 105);
INSERT INTO SYS_ROLE_MENU VALUES (2, 106);
INSERT INTO SYS_ROLE_MENU VALUES (2, 107);
INSERT INTO SYS_ROLE_MENU VALUES (2, 108);
INSERT INTO SYS_ROLE_MENU VALUES (2, 109);
INSERT INTO SYS_ROLE_MENU VALUES (2, 110);
INSERT INTO SYS_ROLE_MENU VALUES (2, 111);
INSERT INTO SYS_ROLE_MENU VALUES (2, 112);
INSERT INTO SYS_ROLE_MENU VALUES (2, 113);
INSERT INTO SYS_ROLE_MENU VALUES (2, 114);
INSERT INTO SYS_ROLE_MENU VALUES (2, 115);
INSERT INTO SYS_ROLE_MENU VALUES (2, 116);
INSERT INTO SYS_ROLE_MENU VALUES (2, 117);
INSERT INTO SYS_ROLE_MENU VALUES (2, 500);
INSERT INTO SYS_ROLE_MENU VALUES (2, 501);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1000);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1001);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1002);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1003);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1004);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1005);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1006);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1007);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1008);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1009);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1010);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1011);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1012);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1013);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1014);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1015);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1016);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1017);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1018);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1019);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1020);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1021);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1022);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1023);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1024);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1025);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1026);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1027);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1028);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1029);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1030);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1031);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1032);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1033);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1034);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1035);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1036);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1037);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1038);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1039);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1040);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1041);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1042);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1043);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1044);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1045);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1046);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1047);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1048);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1049);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1050);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1051);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1052);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1053);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1054);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1055);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1056);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1057);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1058);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1059);
INSERT INTO SYS_ROLE_MENU VALUES (2, 1060);

INSERT INTO SYS_ROLE_MENU
SELECT 1, menu_id FROM SYS_ROLE_MENU;

-- ----------------------------
-- 8、角色和部门关联表  角色1-N部门
-- ----------------------------
DROP TABLE IF EXISTS SYS_ROLE_DEPT;
CREATE TABLE SYS_ROLE_DEPT (
                               ROLE_ID   BIGINT NOT NULL,
                               DEPT_ID   BIGINT NOT NULL,
                               PRIMARY KEY(ROLE_ID, DEPT_ID)
);
-- 单独添加列注释
COMMENT ON COLUMN SYS_ROLE_DEPT.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYS_ROLE_DEPT.DEPT_ID IS '部门ID';
COMMENT ON TABLE SYS_ROLE_DEPT IS '角色和部门关联表';

-- 初始化-角色和部门关联表数据
INSERT INTO SYS_ROLE_DEPT VALUES (2, 100);
INSERT INTO SYS_ROLE_DEPT VALUES (2, 101);
INSERT INTO SYS_ROLE_DEPT VALUES (2, 105);

-- ----------------------------
-- 9、用户与岗位关联表  用户1-N岗位
-- ----------------------------
DROP TABLE IF EXISTS SYS_USER_POST;
CREATE TABLE SYS_USER_POST (
                               USER_ID   BIGINT NOT NULL,
                               POST_ID   BIGINT NOT NULL,
                               PRIMARY KEY (USER_ID, POST_ID)
);
-- 单独添加列注释
COMMENT ON COLUMN SYS_USER_POST.USER_ID IS '用户ID';
COMMENT ON COLUMN SYS_USER_POST.POST_ID IS '岗位ID';
COMMENT ON TABLE SYS_USER_POST IS '用户与岗位关联表';

-- 初始化-用户与岗位关联表数据
INSERT INTO SYS_USER_POST VALUES (1, 1);
INSERT INTO SYS_USER_POST VALUES (2, 2);

-- ----------------------------
-- 10、操作日志记录
-- ----------------------------
DROP TABLE IF EXISTS SYS_OPER_LOG;
CREATE TABLE SYS_OPER_LOG (
                              OPER_ID           BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                              TITLE             VARCHAR(50)     NOT NULL DEFAULT '',  -- 补充NOT NULL，避免空值问题
                              BUSINESS_TYPE     SMALLINT        NOT NULL DEFAULT 0,
                              METHOD            VARCHAR(200)    NOT NULL DEFAULT '',
                              REQUEST_METHOD    VARCHAR(10)     NOT NULL DEFAULT '',
                              OPERATOR_TYPE     SMALLINT        NOT NULL DEFAULT 0,
                              OPER_NAME         VARCHAR(50)     NOT NULL DEFAULT '',
                              DEPT_NAME         VARCHAR(50)     NOT NULL DEFAULT '',
                              OPER_URL          VARCHAR(255)    NOT NULL DEFAULT '',
                              OPER_IP           VARCHAR(128)    NOT NULL DEFAULT '',
                              OPER_LOCATION     VARCHAR(255)    NOT NULL DEFAULT '',
                              OPER_PARAM        VARCHAR(2000)   NOT NULL DEFAULT '',
                              JSON_RESULT       VARCHAR(2000)   NOT NULL DEFAULT '',
                              STATUS            SMALLINT        NOT NULL DEFAULT 0,
                              ERROR_MSG         VARCHAR(2000)   NOT NULL DEFAULT '',
                              OPER_TIME         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              COST_TIME         BIGINT          NOT NULL DEFAULT 0,
                              PRIMARY KEY (OPER_ID)
);
-- 单独添加列注释
COMMENT ON COLUMN SYS_OPER_LOG.OPER_ID IS '日志主键';
COMMENT ON COLUMN SYS_OPER_LOG.TITLE IS '模块标题';
COMMENT ON COLUMN SYS_OPER_LOG.BUSINESS_TYPE IS '业务类型（0其它 1新增 2修改 3删除）';
COMMENT ON COLUMN SYS_OPER_LOG.METHOD IS '方法名称';
COMMENT ON COLUMN SYS_OPER_LOG.REQUEST_METHOD IS '请求方式';
COMMENT ON COLUMN SYS_OPER_LOG.OPERATOR_TYPE IS '操作类别（0其它 1后台用户 2手机端用户）';
COMMENT ON COLUMN SYS_OPER_LOG.OPER_NAME IS '操作人员';
COMMENT ON COLUMN SYS_OPER_LOG.DEPT_NAME IS '部门名称';
COMMENT ON COLUMN SYS_OPER_LOG.OPER_URL IS '请求URL';
COMMENT ON COLUMN SYS_OPER_LOG.OPER_IP IS '主机地址';
COMMENT ON COLUMN SYS_OPER_LOG.OPER_LOCATION IS '操作地点';
COMMENT ON COLUMN SYS_OPER_LOG.OPER_PARAM IS '请求参数';
COMMENT ON COLUMN SYS_OPER_LOG.JSON_RESULT IS '返回参数';
COMMENT ON COLUMN SYS_OPER_LOG.STATUS IS '操作状态（0正常 1异常）';
COMMENT ON COLUMN SYS_OPER_LOG.ERROR_MSG IS '错误消息';
COMMENT ON COLUMN SYS_OPER_LOG.OPER_TIME IS '操作时间';
COMMENT ON COLUMN SYS_OPER_LOG.COST_TIME IS '消耗时间';

-- 创建索引（DB2 支持普通索引语法）
CREATE INDEX IDX_SYS_OPER_LOG_BT ON SYS_OPER_LOG(BUSINESS_TYPE);
CREATE INDEX IDX_SYS_OPER_LOG_S ON SYS_OPER_LOG(STATUS);
CREATE INDEX IDX_SYS_OPER_LOG_OT ON SYS_OPER_LOG(OPER_TIME);

COMMENT ON TABLE SYS_OPER_LOG IS '操作日志记录';

-- ----------------------------
-- 11、字典类型表
-- ----------------------------
DROP TABLE IF EXISTS SYS_DICT_TYPE;
CREATE TABLE SYS_DICT_TYPE (
                               DICT_ID          BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                               DICT_NAME        VARCHAR(100)    NOT NULL DEFAULT '',  -- 补充NOT NULL
                               DICT_TYPE        VARCHAR(100)    NOT NULL DEFAULT '',  -- 关键修复：添加NOT NULL，满足唯一约束要求
                               STATUS           CHAR(1)         NOT NULL DEFAULT '0', -- 补充NOT NULL（建议）
                               CREATE_BY        VARCHAR(64)     NOT NULL DEFAULT '',  -- 补充NOT NULL（建议）
                               CREATE_TIME      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               UPDATE_BY        VARCHAR(64)     NOT NULL DEFAULT '',  -- 补充NOT NULL（建议）
                               UPDATE_TIME      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               REMARK           VARCHAR(500)    DEFAULT NULL,
                               PRIMARY KEY (DICT_ID),
                               UNIQUE (DICT_TYPE)  -- 唯一约束现在合法，因为DICT_TYPE是NOT NULL
);
-- 单独添加列注释
COMMENT ON COLUMN SYS_DICT_TYPE.DICT_ID IS '字典主键';
COMMENT ON COLUMN SYS_DICT_TYPE.DICT_NAME IS '字典名称';
COMMENT ON COLUMN SYS_DICT_TYPE.DICT_TYPE IS '字典类型';
COMMENT ON COLUMN SYS_DICT_TYPE.STATUS IS '状态（0正常 1停用）';
COMMENT ON COLUMN SYS_DICT_TYPE.CREATE_BY IS '创建者';
COMMENT ON COLUMN SYS_DICT_TYPE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_DICT_TYPE.UPDATE_BY IS '更新者';
COMMENT ON COLUMN SYS_DICT_TYPE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYS_DICT_TYPE.REMARK IS '备注';
COMMENT ON TABLE SYS_DICT_TYPE IS '字典类型表';

-- 插入数据（移除自增ID手动赋值）
INSERT INTO SYS_DICT_TYPE (DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('用户性别', 'sys_user_sex', '0', 'admin', CURRENT_TIMESTAMP, '用户性别列表');
INSERT INTO SYS_DICT_TYPE (DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('菜单状态', 'sys_show_hide', '0', 'admin', CURRENT_TIMESTAMP, '菜单状态列表');
INSERT INTO SYS_DICT_TYPE (DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('系统开关', 'sys_normal_disable', '0', 'admin', CURRENT_TIMESTAMP, '系统开关列表');
INSERT INTO SYS_DICT_TYPE (DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('任务状态', 'sys_job_status', '0', 'admin', CURRENT_TIMESTAMP, '任务状态列表');
INSERT INTO SYS_DICT_TYPE (DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('任务分组', 'sys_job_group', '0', 'admin', CURRENT_TIMESTAMP, '任务分组列表');
INSERT INTO SYS_DICT_TYPE (DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('系统是否', 'sys_yes_no', '0', 'admin', CURRENT_TIMESTAMP, '系统是否列表');
INSERT INTO SYS_DICT_TYPE (DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('通知类型', 'sys_notice_type', '0', 'admin', CURRENT_TIMESTAMP, '通知类型列表');
INSERT INTO SYS_DICT_TYPE (DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('通知状态', 'sys_notice_status', '0', 'admin', CURRENT_TIMESTAMP, '通知状态列表');
INSERT INTO SYS_DICT_TYPE (DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('操作类型', 'sys_oper_type', '0', 'admin', CURRENT_TIMESTAMP, '操作类型列表');
INSERT INTO SYS_DICT_TYPE (DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES('系统状态', 'sys_common_status', '0', 'admin', CURRENT_TIMESTAMP, '登录状态列表');

-- ----------------------------
-- 12、字典数据表
-- ----------------------------
DROP TABLE IF EXISTS SYS_DICT_DATA;
CREATE TABLE SYS_DICT_DATA (
                               DICT_CODE        BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                               DICT_SORT        INTEGER         DEFAULT 0,
                               DICT_LABEL       VARCHAR(100)    DEFAULT '',
                               DICT_VALUE       VARCHAR(100)    DEFAULT '',
                               DICT_TYPE        VARCHAR(100)    DEFAULT '',
                               CSS_CLASS        VARCHAR(100)    DEFAULT NULL,
                               LIST_CLASS       VARCHAR(100)    DEFAULT NULL,
                               IS_DEFAULT       CHAR(1)         DEFAULT 'N',
                               STATUS           CHAR(1)         DEFAULT '0',
                               CREATE_BY        VARCHAR(64)     DEFAULT '',
                               CREATE_TIME      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
                               UPDATE_BY        VARCHAR(64)     DEFAULT '',
                               UPDATE_TIME      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
                               REMARK           VARCHAR(500)    DEFAULT NULL,
                               PRIMARY KEY (DICT_CODE)
);
-- 单独添加列注释
COMMENT ON COLUMN SYS_DICT_DATA.DICT_CODE IS '字典编码';
COMMENT ON COLUMN SYS_DICT_DATA.DICT_SORT IS '字典排序';
COMMENT ON COLUMN SYS_DICT_DATA.DICT_LABEL IS '字典标签';
COMMENT ON COLUMN SYS_DICT_DATA.DICT_VALUE IS '字典键值';
COMMENT ON COLUMN SYS_DICT_DATA.DICT_TYPE IS '字典类型';
COMMENT ON COLUMN SYS_DICT_DATA.CSS_CLASS IS '样式属性（其他样式扩展）';
COMMENT ON COLUMN SYS_DICT_DATA.LIST_CLASS IS '表格回显样式';
COMMENT ON COLUMN SYS_DICT_DATA.IS_DEFAULT IS '是否默认（Y是 N否）';
COMMENT ON COLUMN SYS_DICT_DATA.STATUS IS '状态（0正常 1停用）';
COMMENT ON COLUMN SYS_DICT_DATA.CREATE_BY IS '创建者';
COMMENT ON COLUMN SYS_DICT_DATA.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_DICT_DATA.UPDATE_BY IS '更新者';
COMMENT ON COLUMN SYS_DICT_DATA.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYS_DICT_DATA.REMARK IS '备注';
COMMENT ON TABLE SYS_DICT_DATA IS '字典数据表';

-- 插入数据（移除自增ID手动赋值）
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(1, '男', '0', 'sys_user_sex', 'Y', '0', 'admin', CURRENT_TIMESTAMP, '性别男');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(2, '女', '1', 'sys_user_sex', 'N', '0', 'admin', CURRENT_TIMESTAMP, '性别女');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(3, '未知', '2', 'sys_user_sex', 'N', '0', 'admin', CURRENT_TIMESTAMP, '性别未知');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(1, '显示', '0', 'sys_show_hide', 'Y', '0', 'admin', CURRENT_TIMESTAMP, '显示菜单');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(2, '隐藏', '1', 'sys_show_hide', 'N', '0', 'admin', CURRENT_TIMESTAMP, '隐藏菜单');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(1, '正常', '0', 'sys_normal_disable', 'Y', '0', 'admin', CURRENT_TIMESTAMP, '正常状态');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(2, '停用', '1', 'sys_normal_disable', 'N', '0', 'admin', CURRENT_TIMESTAMP, '停用状态');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(1, '正常', '0', 'sys_job_status', 'Y', '0', 'admin', CURRENT_TIMESTAMP, '正常状态');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(2, '暂停', '1', 'sys_job_status', 'N', '0', 'admin', CURRENT_TIMESTAMP, '停用状态');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(1, '默认', 'DEFAULT', 'sys_job_group', 'Y', '0', 'admin', CURRENT_TIMESTAMP, '默认分组');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(2, '系统', 'SYSTEM', 'sys_job_group', 'N', '0', 'admin', CURRENT_TIMESTAMP, '系统分组');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(1, '是', 'Y', 'sys_yes_no', 'Y', '0', 'admin', CURRENT_TIMESTAMP, '系统默认是');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(2, '否', 'N', 'sys_yes_no', 'N', '0', 'admin', CURRENT_TIMESTAMP, '系统默认否');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(1, '通知', '1', 'sys_notice_type', 'Y', '0', 'admin', CURRENT_TIMESTAMP, '通知');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(2, '公告', '2', 'sys_notice_type', 'N', '0', 'admin', CURRENT_TIMESTAMP, '公告');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(1, '正常', '0', 'sys_notice_status', 'Y', '0', 'admin', CURRENT_TIMESTAMP, '正常状态');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(2, '关闭', '1', 'sys_notice_status', 'N', '0', 'admin', CURRENT_TIMESTAMP, '关闭状态');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(99, '其他', '0', 'sys_oper_type', 'N', '0', 'admin', CURRENT_TIMESTAMP, '其他操作');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(1, '新增', '1', 'sys_oper_type', 'N', '0', 'admin', CURRENT_TIMESTAMP, '新增操作');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(2, '修改', '2', 'sys_oper_type', 'N', '0', 'admin', CURRENT_TIMESTAMP, '修改操作');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(3, '删除', '3', 'sys_oper_type', 'N', '0', 'admin', CURRENT_TIMESTAMP, '删除操作');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(4, '授权', '4', 'sys_oper_type', 'N', '0', 'admin', CURRENT_TIMESTAMP, '授权操作');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(5, '导出', '5', 'sys_oper_type', 'N', '0', 'admin', CURRENT_TIMESTAMP, '导出操作');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(6, '导入', '6', 'sys_oper_type', 'N', '0', 'admin', CURRENT_TIMESTAMP, '导入操作');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(7, '强退', '7', 'sys_oper_type', 'N', '0', 'admin', CURRENT_TIMESTAMP, '强退操作');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(8, '生成代码', '8', 'sys_oper_type', 'N', '0', 'admin', CURRENT_TIMESTAMP, '生成操作');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(9, '清空数据', '9', 'sys_oper_type', 'N', '0', 'admin', CURRENT_TIMESTAMP, '清空操作');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(1, '成功', '0', 'sys_common_status', 'N', '0', 'admin', CURRENT_TIMESTAMP, '正常状态');
INSERT INTO SYS_DICT_DATA (DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, REMARK)
VALUES(2, '失败', '1', 'sys_common_status', 'N', '0', 'admin', CURRENT_TIMESTAMP, '停用状态');

-- ----------------------------
-- 13、参数配置表
-- ----------------------------
DROP TABLE IF EXISTS SYS_CONFIG;
CREATE TABLE SYS_CONFIG (
                            CONFIG_ID         INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                            CONFIG_NAME       VARCHAR(100)    DEFAULT '',
                            CONFIG_KEY        VARCHAR(100)    DEFAULT '',
                            CONFIG_VALUE      VARCHAR(500)    DEFAULT '',
                            CONFIG_TYPE       CHAR(1)         DEFAULT 'N',
                            CREATE_BY         VARCHAR(64)     DEFAULT '',
                            CREATE_TIME       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
                            UPDATE_BY         VARCHAR(64)     DEFAULT '',
                            UPDATE_TIME       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
                            REMARK            VARCHAR(500)    DEFAULT NULL,
                            PRIMARY KEY (CONFIG_ID)
);
-- 单独添加列注释
COMMENT ON COLUMN SYS_CONFIG.CONFIG_ID IS '参数主键';
COMMENT ON COLUMN SYS_CONFIG.CONFIG_NAME IS '参数名称';
COMMENT ON COLUMN SYS_CONFIG.CONFIG_KEY IS '参数键名';
COMMENT ON COLUMN SYS_CONFIG.CONFIG_VALUE IS '参数键值';
COMMENT ON COLUMN SYS_CONFIG.CONFIG_TYPE IS '系统内置（Y是 N否）';
COMMENT ON COLUMN SYS_CONFIG.CREATE_BY IS '创建者';
COMMENT ON COLUMN SYS_CONFIG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_CONFIG.UPDATE_BY IS '更新者';
COMMENT ON COLUMN SYS_CONFIG.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYS_CONFIG.REMARK IS '备注';
COMMENT ON TABLE SYS_CONFIG IS '参数配置表';

-- 插入数据（移除自增ID手动赋值）
INSERT INTO SYS_CONFIG (CONFIG_NAME, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, CREATE_BY, CREATE_TIME, REMARK)
VALUES('主框架页-默认皮肤样式名称', 'sys.index.skinName', 'skin-blue', 'Y', 'admin', CURRENT_TIMESTAMP, '蓝色 skin-blue、绿色 skin-green、紫色 skin-purple、红色 skin-red、黄色 skin-yellow');
INSERT INTO SYS_CONFIG (CONFIG_NAME, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, CREATE_BY, CREATE_TIME, REMARK)
VALUES('用户管理-账号初始密码', 'sys.user.initPassword', '123456', 'Y', 'admin', CURRENT_TIMESTAMP, '初始化密码 123456');
INSERT INTO SYS_CONFIG (CONFIG_NAME, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, CREATE_BY, CREATE_TIME, REMARK)
VALUES('主框架页-侧边栏主题', 'sys.index.sideTheme', 'theme-dark', 'Y', 'admin', CURRENT_TIMESTAMP, '深色主题theme-dark，浅色主题theme-light');
INSERT INTO SYS_CONFIG (CONFIG_NAME, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, CREATE_BY, CREATE_TIME, REMARK)
VALUES('账号自助-验证码开关', 'sys.account.captchaEnabled', 'true', 'Y', 'admin', CURRENT_TIMESTAMP, '是否开启验证码功能（true开启，false关闭）');
INSERT INTO SYS_CONFIG (CONFIG_NAME, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, CREATE_BY, CREATE_TIME, REMARK)
VALUES('账号自助-是否开启用户注册功能', 'sys.account.registerUser', 'false', 'Y', 'admin', CURRENT_TIMESTAMP, '是否开启注册用户功能（true开启，false关闭）');
INSERT INTO SYS_CONFIG (CONFIG_NAME, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, CREATE_BY, CREATE_TIME, REMARK)
VALUES('用户登录-黑名单列表', 'sys.login.blackIPList', '', 'Y', 'admin', CURRENT_TIMESTAMP, '设置登录IP黑名单限制，多个匹配项以;分隔，支持匹配（*通配、网段）');
INSERT INTO SYS_CONFIG (CONFIG_NAME, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, CREATE_BY, CREATE_TIME, REMARK)
VALUES('用户管理-初始密码修改策略', 'sys.account.initPasswordModify', '1', 'Y', 'admin', CURRENT_TIMESTAMP, '0：初始密码修改策略关闭，没有任何提示，1：提醒用户，如果未修改初始密码，则在登录时就会提醒修改密码对话框');
INSERT INTO SYS_CONFIG (CONFIG_NAME, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, CREATE_BY, CREATE_TIME, REMARK)
VALUES('用户管理-账号密码更新周期', 'sys.account.passwordValidateDays', '0', 'Y', 'admin', CURRENT_TIMESTAMP, '密码更新周期（填写数字，数据初始化值为0不限制，若修改必须为大于0小于365的正整数），如果超过这个周期登录系统时，则在登录时就会提醒修改密码对话框');

-- ----------------------------
-- 14、系统访问记录
-- ----------------------------
DROP TABLE IF EXISTS SYS_LOGININFOR;
CREATE TABLE SYS_LOGININFOR (
                                INFO_ID        BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                                USER_NAME      VARCHAR(50)     DEFAULT '',
                                IPADDR         VARCHAR(128)    DEFAULT '',
                                LOGIN_LOCATION  VARCHAR(255)    DEFAULT '',
                                BROWSER        VARCHAR(50)     DEFAULT '',
                                OS             VARCHAR(50)     DEFAULT '',
                                STATUS         CHAR(1)         DEFAULT '0',
                                MSG            VARCHAR(255)    DEFAULT '',
                                LOGIN_TIME     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
                                PRIMARY KEY (INFO_ID)
);
-- 单独添加列注释
COMMENT ON COLUMN SYS_LOGININFOR.INFO_ID IS '访问ID';
COMMENT ON COLUMN SYS_LOGININFOR.USER_NAME IS '用户账号';
COMMENT ON COLUMN SYS_LOGININFOR.IPADDR IS '登录IP地址';
COMMENT ON COLUMN SYS_LOGININFOR.LOGIN_LOCATION IS '登录地点';
COMMENT ON COLUMN SYS_LOGININFOR.BROWSER IS '浏览器类型';
COMMENT ON COLUMN SYS_LOGININFOR.OS IS '操作系统';
COMMENT ON COLUMN SYS_LOGININFOR.STATUS IS '登录状态（0成功 1失败）';
COMMENT ON COLUMN SYS_LOGININFOR.MSG IS '提示消息';
COMMENT ON COLUMN SYS_LOGININFOR.LOGIN_TIME IS '访问时间';
-- 创建索引
CREATE INDEX IDX_SYS_LOGININFOR_S ON SYS_LOGININFOR(STATUS);
CREATE INDEX IDX_SYS_LOGININFOR_LT ON SYS_LOGININFOR(LOGIN_TIME);
COMMENT ON TABLE SYS_LOGININFOR IS '系统访问记录';
-- ----------------------------
-- 15、定时任务调度表
-- ----------------------------
DROP TABLE IF EXISTS sys_job;
CREATE TABLE sys_job (
                         job_id              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                         job_name            VARCHAR(64)     NOT NULL DEFAULT '',
                         job_group           VARCHAR(64)     NOT NULL DEFAULT 'DEFAULT',
                         invoke_target       VARCHAR(500)    NOT NULL,
                         cron_expression     VARCHAR(255)    DEFAULT '',
                         misfire_policy      VARCHAR(20)     DEFAULT '3',
                         concurrent          CHAR(1)         DEFAULT '1',
                         status              CHAR(1)         DEFAULT '0',
                         create_by           VARCHAR(64)     DEFAULT '',
                         create_time         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
                         update_by           VARCHAR(64)     DEFAULT '',
                         update_time         TIMESTAMP,
                         remark              VARCHAR(500)    DEFAULT '',
                         PRIMARY KEY (job_id, job_name, job_group)
);
-- 单独添加列注释
COMMENT ON COLUMN sys_job.job_id IS '任务ID';
COMMENT ON COLUMN sys_job.job_name IS '任务名称';
COMMENT ON COLUMN sys_job.job_group IS '任务组名';
COMMENT ON COLUMN sys_job.invoke_target IS '调用目标字符串';
COMMENT ON COLUMN sys_job.cron_expression IS 'cron执行表达式';
COMMENT ON COLUMN sys_job.misfire_policy IS '计划执行错误策略（1立即执行 2执行一次 3放弃执行）';
COMMENT ON COLUMN sys_job.concurrent IS '是否并发执行（0允许 1禁止）';
COMMENT ON COLUMN sys_job.status IS '状态（0正常 1暂停）';
COMMENT ON COLUMN sys_job.create_by IS '创建者';
COMMENT ON COLUMN sys_job.create_time IS '创建时间';
COMMENT ON COLUMN sys_job.update_by IS '更新者';
COMMENT ON COLUMN sys_job.update_time IS '更新时间';
COMMENT ON COLUMN sys_job.remark IS '备注信息';
-- 表注释
COMMENT ON TABLE sys_job IS '定时任务调度表';

-- 插入数据（修正sysdate()为CURRENT_TIMESTAMP，ID改为自增无需指定）
INSERT INTO sys_job (job_name, job_group, invoke_target, cron_expression, misfire_policy, concurrent, status, create_by, create_time, remark)
VALUES('系统默认（无参）', 'DEFAULT', 'ryTask.ryNoParams', '0/10 * * * * ?', '3', '1', '1', 'admin', CURRENT_TIMESTAMP, '');
INSERT INTO sys_job (job_name, job_group, invoke_target, cron_expression, misfire_policy, concurrent, status, create_by, create_time, remark)
VALUES('系统默认（有参）', 'DEFAULT', 'ryTask.ryParams(''ry'')', '0/15 * * * * ?', '3', '1', '1', 'admin', CURRENT_TIMESTAMP, '');
INSERT INTO sys_job (job_name, job_group, invoke_target, cron_expression, misfire_policy, concurrent, status, create_by, create_time, remark)
VALUES('系统默认（多参）', 'DEFAULT', 'ryTask.ryMultipleParams(''ry'', true, 2000L, 316.50D, 100)', '0/20 * * * * ?', '3', '1', '1', 'admin', CURRENT_TIMESTAMP, '');

-- ----------------------------
-- 16、定时任务调度日志表
-- ----------------------------
DROP TABLE IF EXISTS sys_job_log;
CREATE TABLE sys_job_log (
                             job_log_id          BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                             job_name            VARCHAR(64)     NOT NULL,
                             job_group           VARCHAR(64)     NOT NULL,
                             invoke_target       VARCHAR(500)    NOT NULL,
                             job_message         VARCHAR(500),
                             status              CHAR(1)         DEFAULT '0',
                             exception_info      VARCHAR(2000)   DEFAULT '',
                             create_time         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
                             PRIMARY KEY (job_log_id)
);
-- 列注释
COMMENT ON COLUMN sys_job_log.job_log_id IS '任务日志ID';
COMMENT ON COLUMN sys_job_log.job_name IS '任务名称';
COMMENT ON COLUMN sys_job_log.job_group IS '任务组名';
COMMENT ON COLUMN sys_job_log.invoke_target IS '调用目标字符串';
COMMENT ON COLUMN sys_job_log.job_message IS '日志信息';
COMMENT ON COLUMN sys_job_log.status IS '执行状态（0正常 1失败）';
COMMENT ON COLUMN sys_job_log.exception_info IS '异常信息';
COMMENT ON COLUMN sys_job_log.create_time IS '创建时间';
-- 表注释
COMMENT ON TABLE sys_job_log IS '定时任务调度日志表';

-- ----------------------------
-- 17、通知公告表
-- ----------------------------
DROP TABLE IF EXISTS sys_notice;
CREATE TABLE sys_notice (
                            notice_id         INT              NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                            notice_title      VARCHAR(50)     NOT NULL,
                            notice_type       CHAR(1)         NOT NULL,
                            notice_content    BLOB            DEFAULT NULL,
                            status            CHAR(1)         DEFAULT '0',
                            create_by         VARCHAR(64)     DEFAULT '',
                            create_time       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
                            update_by         VARCHAR(64)     DEFAULT '',
                            update_time       TIMESTAMP,
                            remark            VARCHAR(255)    DEFAULT NULL,
                            PRIMARY KEY (notice_id)
);
-- 列注释
COMMENT ON COLUMN sys_notice.notice_id IS '公告ID';
COMMENT ON COLUMN sys_notice.notice_title IS '公告标题';
COMMENT ON COLUMN sys_notice.notice_type IS '公告类型（1通知 2公告）';
COMMENT ON COLUMN sys_notice.notice_content IS '公告内容';
COMMENT ON COLUMN sys_notice.status IS '公告状态（0正常 1关闭）';
COMMENT ON COLUMN sys_notice.create_by IS '创建者';
COMMENT ON COLUMN sys_notice.create_time IS '创建时间';
COMMENT ON COLUMN sys_notice.update_by IS '更新者';
COMMENT ON COLUMN sys_notice.update_time IS '更新时间';
COMMENT ON COLUMN sys_notice.remark IS '备注';
-- 表注释
COMMENT ON TABLE sys_notice IS '通知公告表';

-- 初始化-公告信息表数据（修正ID自增、sysdate()、字符串引号）
INSERT INTO sys_notice (notice_title, notice_type, notice_content, status, create_by, create_time, remark)
VALUES('温馨提醒：2018-07-01 若依新版本发布啦', '2',  CAST('新版本内容' AS BLOB), '0', 'admin', CURRENT_TIMESTAMP, '管理员');
INSERT INTO sys_notice (notice_title, notice_type, notice_content, status, create_by, create_time, remark)
VALUES('维护通知：2018-07-01 若依系统凌晨维护', '1', CAST('维护内容' AS BLOB), '0', 'admin', CURRENT_TIMESTAMP, '管理员');

-- ----------------------------
-- 18、代码生成业务表
-- ----------------------------
DROP TABLE IF EXISTS gen_table;
CREATE TABLE gen_table (
                           table_id          BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                           table_name        VARCHAR(200)    DEFAULT '',
                           table_comment     VARCHAR(500)    DEFAULT '',
                           sub_table_name    VARCHAR(64)     DEFAULT NULL,
                           sub_table_fk_name VARCHAR(64)     DEFAULT NULL,
                           class_name        VARCHAR(100)    DEFAULT '',
                           tpl_category      VARCHAR(200)    DEFAULT 'crud',
                           tpl_web_type      VARCHAR(30)     DEFAULT '',
                           package_name      VARCHAR(100),
                           module_name       VARCHAR(30),
                           business_name     VARCHAR(30),
                           function_name     VARCHAR(50),
                           function_author   VARCHAR(50),
                           gen_type          CHAR(1)         DEFAULT '0',
                           gen_path          VARCHAR(200)    DEFAULT '/',
                           options           VARCHAR(1000),
                           create_by         VARCHAR(64)     DEFAULT '',
                           create_time       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
                           update_by         VARCHAR(64)     DEFAULT '',
                           update_time       TIMESTAMP,
                           remark            VARCHAR(500)    DEFAULT NULL,
                           PRIMARY KEY (table_id)
);
-- 列注释
COMMENT ON COLUMN gen_table.table_id IS '编号';
COMMENT ON COLUMN gen_table.table_name IS '表名称';
COMMENT ON COLUMN gen_table.table_comment IS '表描述';
COMMENT ON COLUMN gen_table.sub_table_name IS '关联子表的表名';
COMMENT ON COLUMN gen_table.sub_table_fk_name IS '子表关联的外键名';
COMMENT ON COLUMN gen_table.class_name IS '实体类名称';
COMMENT ON COLUMN gen_table.tpl_category IS '使用的模板（crud单表操作 tree树表操作）';
COMMENT ON COLUMN gen_table.tpl_web_type IS '前端模板类型（element-ui模版 element-plus模版）';
COMMENT ON COLUMN gen_table.package_name IS '生成包路径';
COMMENT ON COLUMN gen_table.module_name IS '生成模块名';
COMMENT ON COLUMN gen_table.business_name IS '生成业务名';
COMMENT ON COLUMN gen_table.function_name IS '生成功能名';
COMMENT ON COLUMN gen_table.function_author IS '生成功能作者';
COMMENT ON COLUMN gen_table.gen_type IS '生成代码方式（0zip压缩包 1自定义路径）';
COMMENT ON COLUMN gen_table.gen_path IS '生成路径（不填默认项目路径）';
COMMENT ON COLUMN gen_table.options IS '其它生成选项';
COMMENT ON COLUMN gen_table.create_by IS '创建者';
COMMENT ON COLUMN gen_table.create_time IS '创建时间';
COMMENT ON COLUMN gen_table.update_by IS '更新者';
COMMENT ON COLUMN gen_table.update_time IS '更新时间';
COMMENT ON COLUMN gen_table.remark IS '备注';
-- 表注释
COMMENT ON TABLE gen_table IS '代码生成业务表';

-- ----------------------------
-- 19、代码生成业务表字段
-- ----------------------------
DROP TABLE IF EXISTS gen_table_column;
CREATE TABLE gen_table_column (
                                  column_id         BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                                  table_id          BIGINT,
                                  column_name       VARCHAR(200),
                                  column_comment    VARCHAR(500),
                                  column_type       VARCHAR(100),
                                  java_type         VARCHAR(500),
                                  java_field        VARCHAR(200),
                                  is_pk             CHAR(1),
                                  is_increment      CHAR(1),
                                  is_required       CHAR(1),
                                  is_insert         CHAR(1),
                                  is_edit           CHAR(1),
                                  is_list           CHAR(1),
                                  is_query          CHAR(1),
                                  query_type        VARCHAR(200)    DEFAULT 'EQ',
                                  html_type         VARCHAR(200),
                                  dict_type         VARCHAR(200)    DEFAULT '',
                                  sort              INT,
                                  create_by         VARCHAR(64)     DEFAULT '',
                                  create_time       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
                                  update_by         VARCHAR(64)     DEFAULT '',
                                  update_time       TIMESTAMP,
                                  PRIMARY KEY (column_id)
);
-- 列注释
COMMENT ON COLUMN gen_table_column.column_id IS '编号';
COMMENT ON COLUMN gen_table_column.table_id IS '归属表编号';
COMMENT ON COLUMN gen_table_column.column_name IS '列名称';
COMMENT ON COLUMN gen_table_column.column_comment IS '列描述';
COMMENT ON COLUMN gen_table_column.column_type IS '列类型';
COMMENT ON COLUMN gen_table_column.java_type IS 'JAVA类型';
COMMENT ON COLUMN gen_table_column.java_field IS 'JAVA字段名';
COMMENT ON COLUMN gen_table_column.is_pk IS '是否主键（1是）';
COMMENT ON COLUMN gen_table_column.is_increment IS '是否自增（1是）';
COMMENT ON COLUMN gen_table_column.is_required IS '是否必填（1是）';
COMMENT ON COLUMN gen_table_column.is_insert IS '是否为插入字段（1是）';
COMMENT ON COLUMN gen_table_column.is_edit IS '是否编辑字段（1是）';
COMMENT ON COLUMN gen_table_column.is_list IS '是否列表字段（1是）';
COMMENT ON COLUMN gen_table_column.is_query IS '是否查询字段（1是）';
COMMENT ON COLUMN gen_table_column.query_type IS '查询方式（等于、不等于、大于、小于、范围）';
COMMENT ON COLUMN gen_table_column.html_type IS '显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）';
COMMENT ON COLUMN gen_table_column.dict_type IS '字典类型';
COMMENT ON COLUMN gen_table_column.sort IS '排序';
COMMENT ON COLUMN gen_table_column.create_by IS '创建者';
COMMENT ON COLUMN gen_table_column.create_time IS '创建时间';
COMMENT ON COLUMN gen_table_column.update_by IS '更新者';
COMMENT ON COLUMN gen_table_column.update_time IS '更新时间';
-- 表注释
COMMENT ON TABLE gen_table_column IS '代码生成业务表字段';